package com.smgray.easypod.automation

object EasyPodCommands {
    private const val PREFIX = "com.smgray.easypod.command"
    private const val EXTRA_PREFIX = "com.smgray.easypod.extra"

    const val ACTION_UPDATE_SMART_PLAY = "$PREFIX.UPDATE_SMART_PLAY"
    const val ACTION_START_SMART_PLAY = "$PREFIX.START_SMART_PLAY"
    const val ACTION_PLAY = "$PREFIX.PLAY"
    const val ACTION_PAUSE = "$PREFIX.PAUSE"
    const val ACTION_PLAY_PAUSE = "$PREFIX.PLAY_PAUSE"
    const val ACTION_PLAY_NEXT = "$PREFIX.PLAY_NEXT"
    const val ACTION_PLAY_PREVIOUS = "$PREFIX.PLAY_PREVIOUS"
    const val ACTION_SKIP_FORWARD = "$PREFIX.SKIP_FORWARD"
    const val ACTION_SKIP_BACKWARD = "$PREFIX.SKIP_BACKWARD"
    const val ACTION_SKIP_TO_END = "$PREFIX.SKIP_TO_END"
    const val ACTION_SET_PLAYBACK_SPEED = "$PREFIX.SET_PLAYBACK_SPEED"
    const val ACTION_SET_PLAYBACK_SPEED_NORMAL = "$PREFIX.SET_PLAYBACK_SPEED_NORMAL"
    const val ACTION_SET_PLAYBACK_SPEED_1 = "$PREFIX.SET_PLAYBACK_SPEED_1"
    const val ACTION_SET_PLAYBACK_SPEED_2 = "$PREFIX.SET_PLAYBACK_SPEED_2"
    const val ACTION_START_SYNC = "$PREFIX.START_SYNC"

    const val EXTRA_PLAYLIST_ID = "$EXTRA_PREFIX.PLAYLIST_ID"
    const val EXTRA_PLAYBACK_SPEED = "$EXTRA_PREFIX.PLAYBACK_SPEED"

    val SupportedActions = setOf(
        ACTION_UPDATE_SMART_PLAY,
        ACTION_START_SMART_PLAY,
        ACTION_PLAY,
        ACTION_PAUSE,
        ACTION_PLAY_PAUSE,
        ACTION_PLAY_NEXT,
        ACTION_PLAY_PREVIOUS,
        ACTION_SKIP_FORWARD,
        ACTION_SKIP_BACKWARD,
        ACTION_SKIP_TO_END,
        ACTION_SET_PLAYBACK_SPEED,
        ACTION_SET_PLAYBACK_SPEED_NORMAL,
        ACTION_SET_PLAYBACK_SPEED_1,
        ACTION_SET_PLAYBACK_SPEED_2,
        ACTION_START_SYNC,
    )
}
